version: '3.8'
services:
  pos-api:
    container_name: pos-api
    image: api:dev
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/api
    environment:
      - BUN_ENV=development